# @eCommerceServer.WebAPI_HostAddress = http://localhost:5227

GET https://localhost:7178/api/ProductBrands/GetAll
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZmODA4MjA2LTI5NGYtNDQ2NC1lNmM4LTA4ZGM5M2NhMzNiNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJFcmVuIERlbGliYcWfIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiZXJlbkBnbWFpbC5jb20iLCJVc2VyTmFtZSI6ImllZCIsIlVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTkyNjc2OTQsImV4cCI6MTcxOTI2OTQ5NCwiaXNzIjoiRXJlbiBEZWxpYmHFnyIsImF1ZCI6Ikt1bGxhbsSxY8SxbGFyIn0.3W45Tnu6srOw5upS7_XnPT6vJrNQ0ouFkawEa1j2fvWcdOtIoVF-c3sePPkgxoB6O_BmWGl93ukXkmKgXWDRaw

###
